# Generated by Django 2.1.2 on 2019-02-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190211_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='converted_text',
            field=models.TextField(blank=True),
        ),
    ]
