# Generated by Django 2.1.2 on 2019-02-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_document_converted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='selected_lang',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
