# Generated by Django 2.1.7 on 2019-03-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190215_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='session_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
